apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 80
      nodePort: 30007  # Minikube will map this to localhost:443
  selector:
    app: flask-app
